services:
  app:
    image: elvolv/air_quality
    working_dir: /app
    depends_on:
      - database
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./:/app

  database:
    image: postgres:10.13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elvolv
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
